# Site settings
title: Menifesto.nl
email: menifesto@rickpastoor.nl
description: "Menifesto is een maatstaf voor mannen."
baseurl: ""
url: "http://menifesto.nl"
twitter_username: menifesto
github_username:  rickpastoor/menifesto

# Build settings
markdown: kramdown
permalink: pretty

collections:
  hoofdstukken:
    output: true